# Generated by Django 6.0.3 on 2026-03-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bank_bonus_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bvn',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bvn_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='credit_risk_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='credit_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
