# Generated by Django 6.0.3 on 2026-03-13 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=200)),
                ('is_cleared', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='groups.cycle')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='groups.membership')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('membership', 'cycle')},
            },
        ),
    ]
