# Generated by Django 6.0.3 on 2026-03-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_memberdebt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='deposit_paid',
        ),
        migrations.DeleteModel(
            name='DepositTransaction',
        ),
    ]
