# Generated by Django 6.0.3 on 2026-03-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_membership_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('defaulted', 'Defaulted')], default='pending', max_length=25),
        ),
    ]
