# Generated by Django 6.0.3 on 2026-03-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreference',
            name='membership',
        ),
        migrations.AlterField(
            model_name='paymentreference',
            name='payment_type',
            field=models.CharField(choices=[('contribution', 'Cycle Contribution')], max_length=20),
        ),
    ]
